PaperwhiteApp::Application.routes.draw do
	root to: "pages#landing"

	match "/about" => "pages#about"
	match "/contact" => "pages#contact"
	match "/press" => "pages#press"
	match "/stores" => "pages#stores"
	match	"/designer" => "pages#designer"
	match	"/home2" => "pages#home_alt"
	
# Spring 2013
	match "/spring-2013" => "spring13#collection"
	match "drop-shoulder-sweater-and-wide-leg-pant" => "spring13#drop_shoulder_sweater_and_wide_leg_pant"	
	match "3-4-slv-block-linen-tunic" => "spring13#three-quarter-slv-block-linen-tunic"
	match "3-4-slv-printed-blouse-and-stretch-cropped-pant" => "spring13#three_quarter_slv_printed_blouse_and_stretch_cropped_pant"
	match "bib-front-dress-and-bamboo-buckle-belt" => "spring13#bib-front-dress-and-bamboo-buckle-belt"
	match "clip-dot-tank-and-cropped-pant" => "spring13#clip-dot-tank-and-cropped-pant"
	match "crop-jacket-and-floral-print-silk-top" => "spring13#crop-jacket-and-floral-print-silk-top"
	match "drop-shoulder-sweater-and-wide-leg-pant" => "spring13#drop_shoulder_sweater_and_wide_leg_pant"
	match "elbow-sleeve-shirt-dress" => "spring13#elbow-sleeve-shirt-dress"
	match "embroidered-linen-pant" => "spring13#embroidered-linen-pant"
	match "knit-tank-dress-and-skinny-belt-and-waterfall-cardigan" => "spring13#knit-tank-dress-and-skinny-belt-and-waterfall-cardigan"
	match "linen-jacket-and-tank-top-and-slim-legging" => "spring13#linen-jacket-and-tank-top-and-slim-legging"
	match "roll-tab-boyfriend-shirt-and-denim-trousers" => "spring13#roll-tab-boyfriend-shirt-and-denim-trousers"
	match "safari-shirt-jacket-and-printed-capri-pant" => "spring13#safari-shirt-jacket-and-printed-capri-pant"
	match "silk-tank-top-and-clip-dot-scarf" => "spring13#silk-tank-top-and-clip-dot-scarf"
	match "silk-tank-top-and-cropped-pant" => "spring13#silk-tank-top-and-cropped-pant"
	match "sleevless-hi-lo-printed-silk-shirt" => "spring13#sleevless-hi-lo-printed-silk-shirt"
	match "striped-sequin-dress-and-waterfall-cardigan" => "spring13#striped-sequin-dress-and-waterfall-cardigan"

# Fall 2012
	match "/fall-2012" => "fall2012#collection"
	match "/drape-front-jacket" =>  "fall2012#drape_front_jacket"
	match "/faux-leather-blazer" => "fall2012#faux_leather_blazer"
	match "printed-jacket" =>	"fall2012#printed_jacket"
	match "tuxedo-blazer" =>	"fall2012#tuxedo_blazer"
	match "fitted-denim-jacket" =>	"fall2012#fitted_denim_jacket"
	match "faux-leather-motorcycle-jacket" =>	"fall2012#faux_leather_motorcycle_jacket"
	match "sequined-top-riding-pant" =>	"fall2012#sequined_top_riding_pant"
	match "embroidered-plaid-shirt" =>	"fall2012#embroidered_plaid_shirt"
	match "stripe-blouse-wide-leg-pant" =>	"fall2012#stripe_blouse_wide_leg_pant"
	match "printed-knit-top-pleated-skirt" =>	"fall2012#printed_knit_top_pleated_skirt"
	match "novelty-blouse-printed-pant" =>	"fall2012#novelty_blouse_printed_pant"
	match "novelty-pleat-shirt" =>	"fall2012#novelty_pleat_shirt"
	match "ls-printed-shirt" => "fall2012#ls_printed_shirt"
	
	# Spring 2012
	match "spring-2012" 												=> "spring12#spring_collection"
	match "embroidered-shirt"                   => "spring12#embroidered_shirt"
	match "ruched-jacket"                       => "spring12#ruched_jacket"
	match "seersucker-shirt-dress"              => "spring12#seersucker_shirt_dress"
	match "silk-trim-sweater"                   => "spring12#silk_trim_sweater"
	match "printed-tunic"                       => "spring12#printed_tunic"
	match "spring-printed-jacket"               => "spring12#spring_printed_jacket"
	match "sleeveless-striped-dress"            => "spring12#sleeveless_striped_dress"
	match "linen-shirt-dress"                   => "spring12#linen_shirt_dress"
	match "back-button-detail-linen-tunic"      => "spring12#back_button_detail_linen_tunic"
	match "cotton-eyelet-shirt"                 => "spring12#cotton_eyelet_shirt"
	match "printed-floral-shirt"                => "spring12#printed_floral_shirt"
	match "printed-critter-button-up"           => "spring12#printed_critter_button_up"
	match "single-button-jacket"                => "spring12#single_button_jacket"
	match "single-button-linen-jacket"          => "spring12#single_button_linen_jacket"
	match "pintuck-shirt"                       => "spring12#pintuck_shirt"
end